### ISSUE TITLE
phone validation not working 

### ISSUE THREAD

**Issue by rahul9265** [3am-solver/medical-store-app#1]
**Request: **
{
    "name": "rahul",
    "phone": 9265614292,
    "email": "rahulkanjariya9265@gmail.com"

}
**Response:** 
{
    "success": false,
    "msg": {
        "phone": "The Phone maximum is 10",
        "password": "The Password is required",
        "confirm_password": "The Confirm password is required"
    }
}

**Comment by 3am-solver** [comment]
Fixed: 

> Insert phone value as a string litrel
