### ISSUE TITLE
offfers update are not work

### ISSUE THREAD

**Issue by rahul9265** [3am-solver/medical-store-app#2]
<br />
<font size='1'><table class='xdebug-error xe-warning' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Warning: Undefined property: stdClass: :$pid in C:\wamp64\www\nms\api\offers\update.php on line <i>37</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0007</td><td bgcolor='#eeeeec' align='right'>363528</td><td bgcolor='#eeeeec'>{main
}(  )</td><td title='C:\wamp64\www\nms\api\offers\update.php' bgcolor='#eeeeec'>...\update.php<b>:</b>0</td></tr>
</table></font>
<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught PDOException: SQLSTATE[
    42S22
]: Column not found: 1054 Unknown column 'image' in 'field list' [ UPDATE `review` SET `image` = 'aGkuanBn', `discount` = '10', `code` = 'dafsfdfhjf' WHERE `uid` = '3' AND `pid` = NULL
]  in C:\wamp64\www\nms\vendor\opis\database\src\Connection.php on line <i>566</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> PDOException: SQLSTATE[
    42S22
]: Column not found: 1054 Unknown column 'image' in 'field list' [ UPDATE `review` SET `image` = 'aGkuanBn', `discount` = '10', `code` = 'dafsfdfhjf' WHERE `uid` = '3' AND `pid` = NULL
]  in C:\wamp64\www\nms\vendor\opis\database\src\Connection.php on line <i>566</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0007</td><td bgcolor='#eeeeec' align='right'>363528</td><td bgcolor='#eeeeec'>{main
}(  )</td><td title='C:\wamp64\www\nms\api\offers\update.php' bgcolor='#eeeeec'>...\update.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0122</td><td bgcolor='#eeeeec' align='right'>616040</td><td bgcolor='#eeeeec'>Opis\Database\SQL\Update->set( <span>$columns = </span><span>[&#39;image&#39; =&gt; &#39;aGkuanBn&#39;, &#39;discount&#39; =&gt; &#39;10&#39;, &#39;code&#39; =&gt; &#39;dafsfdfhjf&#39;
]</span> )</td><td title='C:\wamp64\www\nms\api\offers\update.php' bgcolor='#eeeeec'>...\update.php<b>:</b>41</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0127</td><td bgcolor='#eeeeec' align='right'>621136</td><td bgcolor='#eeeeec'>Opis\Database\Connection->count( <span>$sql = </span><span>&#39;UPDATE `review` SET `image` = ?, `discount` = ?, `code` = ? WHERE `uid` = ? AND `pid` = ?&#39;</span>, <span>$params = </span><span>[
    0 =&gt; &#39;aGkuanBn&#39;,
    1 =&gt; &#39;10&#39;,
    2 =&gt; &#39;dafsfdfhjf&#39;,
    3 =&gt; &#39;3&#39;,
    4 =&gt; NULL
]</span> )</td><td title='C:\wamp64\www\nms\vendor\opis\database\src\SQL\Update.php' bgcolor='#eeeeec'>...\Update.php<b>:</b>100</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0127</td><td bgcolor='#eeeeec' align='right'>622248</td><td bgcolor='#eeeeec'>Opis\Database\Connection->execute( <span>$prepared = </span><span>[&#39;query&#39; =&gt; &#39;UPDATE `review` SET `image` = ?, `discount` = ?, `code` = ? WHERE `uid` = ? AND `pid` = ?&#39;, &#39;params&#39; =&gt; [
        0 =&gt; &#39;aGkuanBn&#39;,
        1 =&gt; &#39;10&#39;,
        2 =&gt; &#39;dafsfdfhjf&#39;,
        3 =&gt; &#39;3&#39;,
        4 =&gt; NULL
    ], &#39;statement&#39; =&gt; class PDOStatement { public $queryString = &#39;UPDATE `review` SET `image` = ?, `discount` = ?, `code` = ? WHERE `uid` = ? AND `pid` = ?&#39;
    }
]</span> )</td><td title='C:\wamp64\www\nms\vendor\opis\database\src\Connection.php' bgcolor='#eeeeec'>...\Connection.php<b>:</b>439</td></tr>
</table></font>

**Comment by 3am-solver** [comment]
fixed [Reinstall Database]
